### ISSUE TITLE
100% CPU 

### ISSUE THREAD

**Issue by afernandesvigo** [Leoid/B1tMass#2]
When i launch B1tMass for Header Injection, it goes up to 100% of CPU almost freezing the box.

**Comment by Leoid** [comment]
Thanks for your submission. We are currently reviewing your report and will get back to you.

**Comment by Leoid** [comment]
The workers of the Header Injection has been linked to the main one, thus you can modify the number of threads in the whole script by -t/--threads.
Best Regards,
Leo
